### ISSUE TITLE
Indi-3rdparty dependencies

### ISSUE THREAD

**Issue by sc74** [devDucks/astroarch-pkgs#8]
The indi-3rdparty packages have a "PipeWire Media Session" dependency. 

However, ArchWiki recommends "WirePlumber" as a session manager, considering deprecated "PipeWire Media Session". 

Do you plan to follow this recommendation?

**Comment by MattBlack85** [comment]
yes, it's on my very urgent TODO's list

**Comment by MattBlack85** [comment]
this has been solved
