### ISSUE TITLE
Siril 1.2.1 Package

### ISSUE THREAD

**Issue by sc74** [devDucks/astroarch-pkgs#9]
Would it be possible to create the Siril package for aarch64 in order to install it in AstroArch?

**Comment by MattBlack85** [comment]
siril is in the repo now, can you try to install it with pacman @sc74 and report back? thanks!

**Comment by sc74** [comment]
After installing the package, Siril is functional. It's perfect. THANKS!

**Comment by MattBlack85** [comment]
completed
